In [1]:
from datetime import datetime

import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
import metpy.calc as mpcalc
import netCDF4
import numpy as np
import xarray as xr
from cftime import num2pydate
from metpy.units import units
from siphon.catalog import TDSCatalog
from xarray.backends import NetCDF4DataStore

import get_data
import indices
import charts

In [2]:
URL = 'http://thredds.ucar.edu/thredds/catalog/grib/NCEP/GFS/Global_0p25deg/catalog.xml'
dataset = 'Latest Collection for GFS Quarter Degree Forecast'

variables = ['Relative_humidity_isobaric',
             'Temperature_isobaric',
             'u-component_of_wind_isobaric',
             'v-component_of_wind_isobaric',
             'Best_4_layer_Lifted_Index_surface',
             'Geopotential_height_isobaric',
             'Precipitable_water_entire_atmosphere_single_layer']

gfs_data = get_data.GetGFSData(variables)
data = gfs_data.get_data()

Process done in 51.386122941970825 seconds


In [3]:
calculate_indices = indices.CalculateIndices(data)

k_index = calculate_indices.k()
tt_index = calculate_indices.tt()
li_index = calculate_indices.li()
sweat_index = calculate_indices.sweat()

In [4]:
k_index

array([[32.315502 , 32.52246  , 32.437057 , ..., 17.677711 , 18.417677 ,
        18.37962  ],
       [31.266737 , 31.49874  , 31.93873  , ..., 16.965775 , 18.004133 ,
        17.74838  ],
       [30.478146 , 31.336971 , 31.513456 , ..., 16.072084 , 16.28051  ,
        16.233015 ],
       ...,
       [22.296011 , 22.115162 , 22.12896  , ...,  0.8674006,  0.5268438,
         0.4592674],
       [22.325617 , 22.407923 , 22.464912 , ...,  2.6050372,  3.6115882,
         3.5512283],
       [20.993948 , 21.248043 , 21.46239  , ..., 14.477463 , 14.252915 ,
        14.32533  ]], dtype=float32)

In [5]:
tt_index

array([[12.326423 ,  9.8902645,  9.691056 , ..., 23.593132 , 23.55622  ,
        23.737083 ],
       [ 9.957936 , 10.208871 , 10.283251 , ..., 23.504337 , 23.309155 ,
        23.402567 ],
       [10.181439 , 11.61145  , 10.321862 , ..., 23.785868 , 23.524128 ,
        24.319021 ],
       ...,
       [47.192303 , 47.005688 , 46.72311  , ..., 68.33571  , 68.48156  ,
        68.565254 ],
       [47.307507 , 47.164043 , 46.991516 , ..., 67.08063  , 67.120636 ,
        67.14712  ],
       [47.531395 , 47.374943 , 47.24439  , ..., 66.2934   , 66.28213  ,
        66.26936  ]], dtype=float32)

In [6]:
li_index

array([[ 0.05665377, -0.6306448 , -0.8355725 , ..., -0.4369854 ,
        -0.5341595 , -0.33770448],
       [-0.03206271, -0.13625129, -0.33560768, ..., -0.23844865,
        -0.33769944, -0.14124942],
       [ 0.7594847 ,  0.6636532 ,  0.55455196, ..., -0.24122429,
        -0.4335008 , -0.24263223],
       ...,
       [ 5.5615964 ,  5.5629945 ,  5.5622954 , ...,  6.4679523 ,
         6.565141  ,  6.5658402 ],
       [ 5.965835  ,  5.9651365 ,  5.9644175 , ...,  6.2672687 ,
         6.2679577 ,  6.267264  ],
       [ 6.855211  ,  6.7573276 ,  6.755211  , ...,  6.7594547 ,
         6.758047  ,  6.6601634 ]], dtype=float32)

In [7]:
sweat_index

array([[-486.80557 , -589.58    , -557.2755  , ..., -250.44165 ,
        -274.4324  , -259.10474 ],
       [-555.1809  , -542.8036  , -573.6745  , ..., -275.2059  ,
        -286.72083 , -254.93512 ],
       [-582.06433 , -548.1815  , -546.43427 , ..., -234.38339 ,
        -236.4385  , -234.11394 ],
       ...,
       [  38.616596,   34.77585 ,   12.395981, ...,  299.11087 ,
         289.03232 ,  273.72888 ],
       [  41.170074,   42.602146,   43.494144, ...,  286.595   ,
         273.13474 ,  245.86343 ],
       [  48.74751 ,   48.41542 ,   49.267994, ...,  267.23404 ,
         225.91566 ,  269.23257 ]], dtype=float32)